### ISSUE TITLE
Pigz error with pyrodigal

### ISSUE THREAD

**Issue by jasmezz** [nf-core/funcscan#291]
### Description of the bug

We have 2 user reports about failing pipeline runs when using prodigal for annotation:
- https://nfcore.slack.com/archives/C02K5GX2W93/p1684999768853429 (reported by @mathavanpu)
- https://nfcore.slack.com/archives/C02K5GX2W93/p1688471831570479 (reported by @avantonder)

Apparently, pigz as part of the pyrodigal module cannot process certain samples, see screenshot below.

### Command used and terminal output

```console
nextflow run nf-core/funcscan -profile singularity -c cambridge.config --input samplesheet.csv --run_amp_screening --run_arg_screening --amp_skip_hmmsearch -resume --outdir funcscan_results

(See error screenshot below)
```

### Relevant files

Error screenshot from @avantonder:
![funcscan_error](https://github.com/nf-core/funcscan/assets/73216762/ec1f5eb7-2543-4382-921a-d3b85935858f)

**Comment by tetedange13** [comment]
Hi,

For the 1st `pigz -cdf ${fasta}` call, my understanding is that you want to be able to handle both compressed and uncompressed input fasta ?
=> Maybe you could consider using [**seqkit**](https://github.com/shenwei356/seqkit), which already does that under the hood ?

Kind regards,
Felix.

**Comment by jfy133** [comment]
Thanks for the suggestion @tetedange13! Could be worth considering - however we would rather not have to maintainer a different custom container ourselves (which is already a little awkawrd). I think we just need to check the pattern that picks up the files

**Comment by jfy133** [comment]
Actually I can't even replicate the error on my own machine... when gzipping a symlink (works fine for me) 

IIn fact, why are we even using a custom container that includes `pigz` when pigz isn't even specified to use multiple threads, which is the only advantage?!

**Comment by jfy133** [comment]
@jasmezz @louperelo can you advise/

**Comment by jasmezz** [comment]
The original problem of this issue is not the `pigz -cdf ${fasta}`, but the `pigz -nm ${prefix}*` which apparently couldn't handle symlinks. I am pulling the updated module right now which should solve that.

**Comment by AmayAgrawal** [comment]
I am actually still experiencing this issue while running the latest (1.1.3) verison of the pipeline

**Comment by jfy133** [comment]
> I am actually still experiencing this issue while running the latest (1.1.3) verison of the pipeline. Below is the sreenshot of the error that I got
> ![Screenshot from 2023-09-28 11-10-47](https://github.com/nf-core/funcscan/assets/12967238/be085578-1268-4ef3-9a15-99141192e964)
> 
> 
> 

What command did you use to execute the pipeline?
